import type { NextPage } from "next";
import Head from "next/head";

import Hero from "src/sections/hero";
import Navbar from "src/components/Navbar";
import styles from "styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hacktober Fest 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Hero />

      <div className={styles.container}>
        <main className={styles.main}>
          <h1>Hello</h1>
        </main>
      </div>
    </div>
  );
};

export default Home;
